### ISSUE TITLE
[Class2] ScrollApp - Rozjeżdżenie się zdjęć podczas szybkiego scrollowania

### ISSUE THREAD

**Issue by TomoLV** [DaftMobile/ioslevelup_2018#1]
Zauważyłem, że podczas szybkiego scrollowania zdjęć, rozjeżdża się ramka obecnie wyświetlanego obrazka i widać część zdjęcia, które powinno być wyświetlane oraz część zdjęcia kolejnego (bądź poprzedniego, w zależności od tego, w którą stronę scrollowaliśmy). Podczas powolnego scrollowania ramka się nie rozjeżdża.

Załączam gifa obrazującego ten problem:
![scrollappissue](https://user-images.githubusercontent.com/4348715/38098196-aaf6036c-3377-11e8-8a47-0b3dae50d451.gif)

**Comment by mdab121** [comment]
Problem jest związany z faktem, że w implementacji `recenterIfNecessary()` robię przesunięcie zawsze do środka, a nie o całkowitą liczbę stron (a to ScrollView ma włączony paging).
2. Efekt jest taki, że kiedy scrollujesz bardzo szybko, to czasem nie istnieje taka klatka, w której przesunięcie jest o całą stronę (bo było na tyle szybko że przesuwało się o więcej niż 1 point / frame (frame z framerate'u, a nie frame z UIKitu))
3. W takich przypadkach i tak przesuwam do środka całośc, i rzeczy lądują na nie - do - końca wyrównanych z pagingiem miejscach.

Poprawiam zmieniając skok na taki o dokładnie całkowitą liczbę stron (bounds.width).
Ale w przypadku scrollview, w którym paging jest **wyłączony** lepsze jest użycie poprzedniego podejścia!
